[package]
name = "aufind"
version = "0.1.2"
authors = ["kykc"]
edition = "2015"

[lib]
name = "aufindlib"
path = "src/lib.rs"

[[bin]]
name = "aufind"
path = "src/main.rs"

[dependencies]
walkdir = "*"
regex = "*"
clap = "^2.32"
rustyline = "^2.1"
colored = "^1.6"
dirs = "*"
